(set! gameCamera.SubjectDistance 10)
(set! game.CameraUp @(0 0 -1))
(set! game.CameraPosition (vector -40 30 -50))
(set! game.CameraTargetLocation (vector -40 0 -50))

(define-state-machine moveCamera
  (start (when (key-down? Keys.Up)
	   (set! game.CameraPosition (+ game.CameraPosition (vector 0 0 -1)))
	   (set! game.CameraTargetLocation (+ game.CameraTargetLocation (vector 0 0 -1))))
	 (when (key-down? Keys.Down)
	   (set! game.CameraPosition (+ game.CameraPosition (vector 0 0 1)))
	   (set! game.CameraTargetLocation (+ game.CameraTargetLocation (vector 0 0 1))))
	 (when (key-down? Keys.Left)
	   (set! game.CameraPosition (+ game.CameraPosition (vector -1 0 0)))
	   (set! game.CameraTargetLocation (+ game.CameraTargetLocation (vector -1 0 0))))
	 (when (key-down? Keys.Right)
	   (set! game.CameraPosition (+ game.CameraPosition (vector 1 0 0)))
	   (set! game.CameraTargetLocation (+ game.CameraTargetLocation (vector 1 0 0))))
	 (when (key-down? Keys.Z)
	   (set! game.CameraPosition (+ game.CameraPosition (vector 0 1 0)))
	   (set! game.CameraTargetLocation (+ game.CameraTargetLocation (vector 0 1 0))))
	 (when (key-down? Keys.X)
	   (set! game.CameraPosition (+ game.CameraPosition (vector 0 -1 0)))
	   (set! game.CameraTargetLocation (+ game.CameraTargetLocation (vector 0 -1 0))))))